[project]
name = "task-manager"
version = "0.1.0"
description = "just a simple task manager for crud refresh"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
    "django-bootstrap5>=25.3",
    "django-browser-reload>=1.21.0",
]
